---
title: "Eduardo Girardi's CV"
author: Eduardo Girardi
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1IDKm2jIqQKrlsQ7omx2sGlZ8qCaTS8fJRe1dyG0Fnm0/edit?usp=sharing",  
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _nickstrayer.me/datadrivencv/_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://github.com/eduardogirardi/meucv/tree/main/docs/cv.pdf)")
}
```

Contatos {#contact}
--------------------------------------------------------------------------------

```{r}
CV |> print_contact_info()
```



Linguagens {#skills}
--------------------------------------------------------------------------------

```{r}
CV |> print_skill_bars()
```


Modelagem {#molskills}
--------------------------------------------------------------------------------

```{r}
CV$molskill <- tibble::tribble(
  ~skill, ~level,
  "Reg. - Linear",   4,
  "Reg. - Não linear",   3,
  "Reg. - Efeito misto",   3,
  "ML - Random forest",   4,
  "ML - Redes neurais",   1
  )

print_molskill_bars <- function(
  cv, 
  out_of = 5, 
  bar_color = "#969696", 
  bar_background = "#d9d9d9",
  glue_template = "default"
  ) {
    if (glue_template == "default") {
    glue_template <- "
<div
class = 'skill-bar'
style = \"background:linear-gradient(to right,
           {bar_color} {width_percent}%,
           {bar_background} {width_percent}% 100%)\"
>{skill}</div>"
  }

  cv$molskill |>
    dplyr::mutate(width_percent = round(100 * as.numeric(level) / out_of)) |>
    glue::glue_data(glue_template) |>
    print()

  invisible(cv)
}

CV |> print_molskill_bars()
```

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

Main
================================================================================

Eduardo Girardi {#title}
--------------------------------------------------------------------------------

```{r}
# Note the assignment back to CV. This is so the link stripping works properly in PDF mode
CV <- print_text_block(CV, "intro") 
```

Formação {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'education')
```


Experiencia Profissional {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'industry_positions')
```

<br>


<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>


Publicaçoes selecionadas {data-icon=book}
--------------------------------------------------------------------------------

```{r}
CV <- print_section(CV, 'academic_articles')
```



```{r}
print_links(CV)
```

